// functions:
#define imprimerf printf 
#define fimprimerf fprintf 
#define simprimerf sprintf 
#define principal main
#define scanf scanf
#define longueur strlen
#define allocm malloc
#define allocc calloc
#define places puts
#define placec putc
#define obtenirs gets
#define obtenirc getc
#define fouvrir fopen
#define ffermer fclose
#define taillede sizeof

// control flow:
#define si if
#define sinon else
#define pour for
#define tantque while
#define faire do
#define pour for
#define pendant while
#define interrupteur switch
#define cas case
#define defaut default
#define retourner return 
#define continue continuer
#define arrêt break
#define allerà goto

// data types:
#define double double 
#define vide void
#define vrai true
#define faux false
#define signé signed
#define nonsigné unsigned
#define déftype typedef
#define court short
#define énum enum
#define caractère char
#define ent int
#define flottant float
